language: node_js

node_js:
  - '6'
  - '8'

dist: trusty
sudo: true

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6

notifications:
  email:
    smcarthur@mozilla.com
    jrgm@mozilla.com
  irc:
    channels:
      - 'irc.mozilla.org#fxa-bots'
    use_notice: false
    skip_join: false

env:
  - CXX=g++-4.8 NODE_ENV=test DB=memory
  - CXX=g++-4.8 NODE_ENV=test DB=mysql

before_install:
  - npm i -g npm@5
  - npm config set spin false

install:
  - npm ci 

before_script:
  - "mysql -u root -NBe 'select version()'"
  - "mysql -u root -e 'DROP DATABASE IF EXISTS fxa_oauth;'"
  - "mysql -u root -e 'CREATE DATABASE fxa_oauth CHARACTER SET utf8 COLLATE utf8_unicode_ci;'"

script:
  - npm run outdated
  - npm test
  - grunt nsp --force
