language: node_js

node_js:
  - '0.10'

notifications:
  email:
    smcarthur@mozilla.com
    jrgm@mozilla.com
  irc:
    channels:
      - 'irc.mozilla.org#fxa'
    use_notice: false
    skip_join: false

env:
  - NODE_ENV=test DB=memory
  - NODE_ENV=test DB=mysql

before_script:
  - "mysql -NBe 'select version()'"
  - sudo apt-get install libgmp3-dev
  - "mysql -e 'DROP DATABASE IF EXISTS fxa_oauth;'"
  - "mysql -e 'CREATE DATABASE fxa_oauth;'"

script:
  - grunt validate-shrinkwrap test
